### ISSUE TITLE
Do the bindings in basic.cpp work?

### ISSUE THREAD

**Issue by Sciss** [gwsounddsg/wasm-embind#1]
Hi there. I am struggling with understanding how to successfully use [Embind's EMSCRIPTEN_BINDINGS](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#classes), somehow I don't see the symbols in the generated js. Did you manage to get `myPrint` in `lib/basic.cpp` exported and callable from js? If so, what's the trick to run em++? Thanks

**Comment by Sciss** [comment]
Nevermind, I got `EMSCRIPTEN_BINDINGS` [working](https://github.com/Sciss/EmbindTest/blob/main/classes_post.cpp) finally.

**Comment by gwsounddsg** [comment]
@Sciss Hey, sorry I'm just now seeing this. Glad you got it to work!
